### ISSUE TITLE
Single Player Crash Related to stairs and mineshafts

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#101]
I'm not sure what I did on the world, but I was experimenting with mineshafts, and now game crashes when i place the mineshaft token.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
Contact their authors BEFORE contacting forge

// Shall we play a game?

Time: 4/10/19 6:31 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.world.World.func_189509_E(World.java:225)
	at net.minecraft.world.World.func_180495_p(World.java:905)
	at net.tangotek.villagerplus.structures.VillageStructureMineshaft.canMine(VillageStructureMineshaft.java:170)
	at net.tangotek.villagerplus.structures.VillageStructureMineshaft.validate(VillageStructureMineshaft.java:294)
	at net.tangotek.villagerplus.structures.VillageStructure.setup(VillageStructure.java:71)
	at net.tangotek.villagerplus.structures.VillageStructure.<init>(VillageStructure.java:58)
	at net.tangotek.villagerplus.structures.VillageStructureMineshaft.<init>(VillageStructureMineshaft.java:31)
	at net.tangotek.villagerplus.structures.VillageStructureType$3.create(VillageStructureType.java:31)
	at net.tangotek.villagerplus.structures.VillageStructureFactory.create(VillageStructureFactory.java:25)
	at net.tangotek.villagerplus.VillageManager.procesScanBoxes(VillageManager.java:109)
	at net.tangotek.villagerplus.VillageManager.update(VillageManager.java:72)
	at net.tangotek.villagerplus.TekVillager$RegistrationHandler.worldTick(TekVillager.java:179)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_17_RegistrationHandler_worldTick_WorldTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:274)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_191, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1115665240 bytes (1063 MB) / 1744830464 bytes (1664 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2768 17 mods loaded, 17 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version                      | Source                                                         | Signature                                |
	|:--------- |:------------------- |:---------------------------- |:-------------------------------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2                       | minecraft.jar                                                  | None                                     |
	| UCHIJAAAA | mcp                 | 9.42                         | minecraft.jar                                                  | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99                    | forge-1.12.2-14.23.5.2768.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.5.2768                 | forge-1.12.2-14.23.5.2768.jar                                  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | betterbuilderswands | 0.13.2                       | BetterBuildersWands-1.12.2-0.13.2.271+5997513.jar              | None                                     |
	| UCHIJAAAA | chiselsandbits      | 14.31                        | chiselsandbits-14.31.jar                                       | None                                     |
	| UCHIJAAAA | craftstudioapi      | 1.0.0                        | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar             | None                                     |
	| UCHIJAAAA | inventorytweaks     | 1.63+release.109.220f184     | InventoryTweaks-1.63.jar                                       | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJAAAA | ironchest           | 1.12.2-7.0.59.842            | ironchest-1.12.2-7.0.59.842.jar                                | None                                     |
	| UCHIJAAAA | jei                 | 4.15.0.273                   | jei_1.12.2-4.15.0.273.jar                                      | None                                     |
	| UCHIJAAAA | laggoggles          | FORGE-1.12.2-4.1             | LagGoggles-FORGE-1.12.2-4.1.jar                                | None                                     |
	| UCHIJAAAA | llor                | 1.1.6-mc1.12.2               | LLOverlayReloaded-1.1.6-mc1.12.2.jar                           | None                                     |
	| UCHIJAAAA | moreoverlays        | 1.14                         | moreoverlays-1.14-mc1.12.2.jar                                 | None                                     |
	| UCHIJAAAA | villagerplus        | 1.0.0                        | villagerplus-1.0 (5).jar                                       | None                                     |
	| UCHIJAAAA | wawla               | 2.5.269                      | Wawla-1.12.2-2.5.269.jar                                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| UCHIJAAAA | worldedit           | 6.1.10-SNAPSHOT              | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar              | None                                     |
	| UCHIJAAAA | worldeditcuife2     | 2.2.0-mf-1.12.2-14.23.5.2768 | WorldEdit CUI Forge Edition 2-2.2.0-mf-1.12.2-14.23.5.2768.jar | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['gotnate'/127, l='superflat', x=-601.31, y=34.00, z=-390.64]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by gotnate** [comment]
I am beginning to suspect it's both an excessive number of stairs in the mineshaft combined with a left turn, possibly near the edge of the village zone. when i reopen the world, the mineshaft marker does not light up until i load the chunks with the town hall

**Comment by TangoTek** [comment]
Fixed
