### ISSUE TITLE
Suggestion: Miners craft torches

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/What-If-Villager-Community#103]
You mentioned at some point that you haven't made miners craft their torches because you didn't think miners would be able to harvest sufficient coal in order to craft torches for themselves. But in #84 you said that a drain on the log supply is needed. Two birds, one stone: make miners craft their torches, but preferentially use charcoal over coal in order to do it.

Even with the vanilla recipe efficiency, this would allow the miner to use up a full 18 logs per stack of torches.

**Comment by TangoTek** [comment]
Hmm. Should the miners smelt charcoal?  Currently only the blacksmith does that.

**Comment by TangoTek** [comment]
Not a bad idea though.

**Comment by TheGreatNaj** [comment]
I think it would be better if miners smelted charcoal making the blacksmiths focus more on smelting ore too

**Comment by TangoTek** [comment]
They both smelt logs into coal now. Miners craft their own torches. I think there is plenty of downtime for the Blacksmith so it makes sense for him to help out when he has time.
