### ISSUE TITLE
Lumberjacks will convert items thrown to them

### ISSUE THREAD

**Issue by OhTheNoises** [TangoTek/What-If-Villager-Community#11]
if you throw logs to a lumberjack it will not convert them when they suck them up but they will convert oak logs to V-Items when they drop them off at storage. 

EDIT: More testing, if they have a partial stack of any wood type already as a villager item they will convert and collect that other type and turn it into a V-Item

**Comment by GrifterMage** [comment]
This also applies to farmers with their crops; probably other villager types as well, but I haven't tested those.

**Comment by TangoTek** [comment]
Fixed issues with v-items and non v-items stacking on villagers and in storage
