### ISSUE TITLE
Villagers spawned from a monster spawner quickly starve to death

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#115]
They seem to hit the world hungry and with low health.

![image](https://user-images.githubusercontent.com/69241/56100536-ca311900-5ece-11e9-818d-b0d5228783c7.png)

**Comment by gotnate** [comment]
![image](https://user-images.githubusercontent.com/69241/56100962-c784f280-5ed3-11e9-89cd-9d43219e56b4.png)

**Comment by TangoTek** [comment]
Not really concerned with this to be honest.
