### ISSUE TITLE
Glowing Miners

### ISSUE THREAD

**Issue by MakaniValur** [TangoTek/What-If-Villager-Community#118]
So, I'm not sure what is causing this, since none of them are injured in any way, but my miners have been mining something that's causing them to glow... 

<img width="211" alt="Screenshot 2019-04-15 at 16 31 57" src="https://user-images.githubusercontent.com/49378993/56145647-96bcc000-5f9c-11e9-9720-91b43f042c88.png">

As I said, perfectly healthy:
<img width="376" alt="Screenshot 2019-04-15 at 16 32 00" src="https://user-images.githubusercontent.com/49378993/56145689-a805cc80-5f9c-11e9-9d3f-2d48911d0f0d.png">

And oh goodness it's contagious!
<img width="847" alt="Screenshot 2019-04-15 at 16 33 49" src="https://user-images.githubusercontent.com/49378993/56145711-b522bb80-5f9c-11e9-9624-31179b83bb9f.png">

**Comment by TangoTek** [comment]
Just some debug stuff I put in while I was working on Miners. Forgot to take it out.  Its out now.
