### ISSUE TITLE
Farmers refusing to plant

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/What-If-Villager-Community#12]
Farmers don't plant any crop unless there are already crops of the same type planted in an adjacent farmland block--the video mentioned they should plant a random crop in that situation, but they don't plant anything.

Farmers also will not plant a seed crop if they only have one item of that type in their inventory.

**Comment by TangoTek** [comment]
Fixed the second issue. 

Regarding planting and adjacency.  They won't plant on a square that has no other crops adjacent.  In the video I mentioned (or at least intended to) that it was random what crop they'd plant only if its a 'tie' between the number of adjacent crops
