### ISSUE TITLE
No animal babies

### ISSUE THREAD

**Issue by MakaniValur** [TangoTek/What-If-Villager-Community#122]
I have had the consistent issue of my animals not procreating. To get to the bottom of it I ended up setting up a mini village of just a farmer and a rancher and watched what the rancher did. 

It seems like he only ever feeds one animal at the time, meaning that the time elapsed between feeding two animals is too long to make them stay in breeding mode. 

In my big village, with multiple ranchers, I do get babies (albeit very rarely) whenever two farmers happen to feed the animals at the same time or shortly after one another. 

It also gets better the more starting animals I have for some reason. But I assume in a normal setup, most people will start with two animals so it takes forever for the first villager animal baby to appear. (I left the game running in my mini village for about an hour and didn't get a single baby animal)

**Comment by LiteHorizon** [comment]
Fixed
