### ISSUE TITLE
Miners torch issues

### ISSUE THREAD

**Issue by MakaniValur** [TangoTek/What-If-Villager-Community#126]
My miners are all unhappily looking for torches, problem is, they are also grabbing all my wood reserves and smelt it up into charcoal. 

A little while ago I looked at all my chests and I hadn't got a single log, but instead *did* have about 20 stacks of charcoal.

Meanwhile, when the lumberjack brought some more logs, the blacksmith immediately grabbed them to make more charcoal. 

Something is definitely borked there.

<img width="821" alt="Screenshot 2019-04-18 at 23 07 57" src="https://user-images.githubusercontent.com/49378993/56395331-14e5c480-6232-11e9-8b61-70c450f6d1d9.png">

**Comment by LiteHorizon** [comment]
so looking into this, it seems that the blacksmith is once again turning all the logs into charcoal and he (and) the miners will take it out of the furnace and put it into storage (miners only take out charcoal they won't put any into one) and never craft torches.

**Comment by TangoTek** [comment]
They should no longer smelt wood into charcoal once there is 16 charcoal in storage.
