### ISSUE TITLE
Sapling shortage

### ISSUE THREAD

**Issue by MakaniValur** [TangoTek/What-If-Villager-Community#127]
So I've noticed this more and more - the lumberjacks are not replanting but there are loads of saplings dropping around where the tree was. I'm not sure what the solution is but it's a bit of a problem....

<img width="821" alt="Screenshot 2019-04-18 at 23 09 31" src="https://user-images.githubusercontent.com/49378993/56395495-c1c04180-6232-11e9-8e9e-f45c08c26c62.png">

**Comment by LiteHorizon** [comment]
one solution could be that they always get one sapling to replant

**Comment by TangoTek** [comment]
This should be fixed.  They will now pick up to 32 saplings of each type.
