### ISSUE TITLE
Feature Request: Tavern visits

### ISSUE THREAD

**Issue by MakaniValur** [TangoTek/What-If-Villager-Community#129]
So, in all the time I've had my village, I have had one single villager visit the tavern. And it was only because I killed loads of other villagers in front of him to make him unhappy enough to want to go.

Could you maybe add something like a 30% chance that the villager will go to the tavern on any evening? That way it would seem more lively and you don't have to actually make the tavern seem more frequented without you having to torture your villagers for it.

**Comment by LiteHorizon** [comment]
Added
