### ISSUE TITLE
Farmers retrieving seed crops from storage

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/What-If-Villager-Community#13]
When a farmer runs out of seed crops on hand, they can't plant more until they harvest more crops, because only then will they have seeds to plant.

If there are seeds of the appropriate kind in storage and farmland available, it would make sense for farmers with plantable farmland available to fetch those seeds so they can continue planting.

**Comment by TangoTek** [comment]
They do get seeds.  They did it in the lumberjack video in fact.  I'll see if I can reproduce though.

**Comment by GrifterMage** [comment]
If it helps, I was working with carrots; those were the only items in storage.
