### ISSUE TITLE
Bard is tavernicating outside my small tavern

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#134]
![image](https://user-images.githubusercontent.com/69241/56404079-8402ef00-6219-11e9-9241-c6d9ad4a4f75.png)

**Comment by gotnate** [comment]
she did go inside with a larger tavern

**Comment by TangoTek** [comment]
Not going to fix this. The difficulty and risk it introduces isn't worth the rarity of this happening.
