### ISSUE TITLE
Child Intelligence too high

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/What-If-Villager-Community#148]
**Is your feature request related to a problem? Please describe.**
Children gain intelligence too fast. I currently have a child that has 97 intelligence

**Describe the solution you'd like**
Intelligence in a child should cap at a certain point. Not sure what the correct number is but they should not be able to max it out

**Describe alternatives you've considered**
A child should not be able to receive such a high intelligence. Either a cap should be applied before they turn into an adult or their child intelligence level should be converted into an adult intelligence level.

**Additional context**
![2019-04-25_22 59 07](https://user-images.githubusercontent.com/49371154/56771455-97c8cb00-67ae-11e9-9a9d-4835bc3c3a08.png)

**Comment by TangoTek** [comment]
Somewhat related... how do you feel about the rate school teachers are increasing their Teacher skill?

**Comment by TangoTek** [comment]
Would you say most of your teaching was from the teacher consuming books? or from random individual teaching?

**Comment by TangoTek** [comment]
Lowered the overall learn rate of kids a bit. 
More importantly, I made intelligence gains for all villagers become harder as you your intelligence gets higher. 
So low intelligence villagers can/will gain intelligence quickly, but high intelligence villagers will gain it a bit slower.
