### ISSUE TITLE
Butcher takes animals to kill but doesn't have an ax.

### ISSUE THREAD

**Issue by LiteHorizon** [TangoTek/What-If-Villager-Community#150]
the butcher will keep taking animals the butcher structure when he doesn't have an ax

![image](https://user-images.githubusercontent.com/39017085/56773870-bebed700-6785-11e9-9f97-3c4ab8bf435c.png)

**Comment by TangoTek** [comment]
This was a conscious decision.  Should he stop doing all his work because he can't do the end of it?

Maybe he should stop bringing animals over once he has 4 or 5 in the butcher shop?

**Comment by LiteHorizon** [comment]
4-5 would be good. this is overkill lol

![2019-04-25_19 56 58](https://user-images.githubusercontent.com/39017085/56854053-2dbb3d80-68f6-11e9-8351-04b248420e29.png)
