### ISSUE TITLE
Miners not depositing Lapis

### ISSUE THREAD

**Issue by MakaniValur** [TangoTek/What-If-Villager-Community#175]
Pretty much all my miners have lapis in their inventory and have done for days but they don't seem to deposit it.

Had to add some to the chest myself or else the Enchantress wouldn't have been able to do her job...

<img width="846" alt="Screenshot 2019-05-11 at 15 13 17" src="https://user-images.githubusercontent.com/49378993/57570166-7b0fd280-73ff-11e9-9b9f-564e7f62ca27.png">

**Comment by TangoTek** [comment]
Good catch! Lapis internally is just another type of Dye. I was forgetting to set the subtype (Blue) on the delivery rules.  Fixed. Thanks!
