### ISSUE TITLE
Villagers void items thrown at them

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#18]
If you throw some items at villagers (bedrock, cooked steak) they pick them up, and you see them in their inventory for a moment, and then they disappear. Bedrock was due to experimentation of _what_ they'll pick up. Steak was because they were hungry and i wanted to feed the hungry villager

**Comment by TangoTek** [comment]
Was this a Miner?

**Comment by TangoTek** [comment]
Assuming it was a Miner. Fixed for him.

**Comment by gotnate** [comment]
i think it was a rancher
