### ISSUE TITLE
Divide and Conquer AI

### ISSUE THREAD

**Issue by TheGreatNaj** [TangoTek/What-If-Villager-Community#181]
Villagers of the same job really tend to go after the same areas, like I usually find my druids either both at the mines or both at the farms and the farmers focus on one crop mainly if they're all full (usually whichever is closes). Itd be nice if there was some kind of AI telling them to search for a job more farther away from others already doing their job.

**Comment by TangoTek** [comment]
Druids intentionally split the day in half. Morning they grow crops/trees, afternoon they go into the mines. This is to avoid spending half their time going back and forth as the travel time to the mines can be lengthy.

Farmer crop priority is on my list for getting a full redo.

Also, you are hinting at having the villager AI tweaker feature, which I very much want to do.  Each villager would have an expanded right-click UI where you could prioritize their different AI components.
