### ISSUE TITLE
Merchant wants impossible trades.

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#20]
Eggs only stack to 16

![image](https://user-images.githubusercontent.com/69241/55677730-eebf3c80-58a1-11e9-9df0-840c355f6b45.png)

**Comment by gotnate** [comment]
Beet Root Soup doesn't stack at all

![image](https://user-images.githubusercontent.com/69241/55693869-3ad3b500-5966-11e9-99a0-f1995b9dd739.png)

**Comment by TangoTek** [comment]
Eggs changed to 16. Soup removed.
