### ISSUE TITLE
Guards taking 6 logs out of storage but already has a sword in hand  

### ISSUE THREAD

**Issue by LiteHorizon** [TangoTek/What-If-Villager-Community#22]
![TV1](https://user-images.githubusercontent.com/39017085/55678788-27bcd880-58c5-11e9-91b0-a42d2c0547f2.png)

**Comment by gotnate** [comment]
All the villagers are hoarding extra logs 
![image](https://user-images.githubusercontent.com/69241/55678898-4ff10b00-58b6-11e9-864f-6ae6c366611d.png)

**Comment by LiteHorizon** [comment]
maybe its intended.. but it uses up most of your logs in the early game play

**Comment by TangoTek** [comment]
Fixed.
