### ISSUE TITLE
Possible Server Crashing bug

### ISSUE THREAD

**Issue by DropDaBassTC** [TangoTek/What-If-Villager-Community#3]
**Describe the bug**
Started a new village in the buildings of an existing one.  Set up a storage room and a town hall (in that order) and then went to go place chests in the storage room, opened the door with the town hall icon in my hand and the server immediately went down.

**To Reproduce**
1. Have Town hall icon in hand
2. Click on Existing door

**Expected behavior**
Server will immediately crash

**Screenshots**
No screenshots available

**Comment by TangoTek** [comment]
Tested this.  The crash must have been unrelated.
