### ISSUE TITLE
Miner's items disappear

### ISSUE THREAD

**Issue by TheGreatNaj** [TangoTek/What-If-Villager-Community#31]
I had a miner with a stack of 5 and 9 redstone in its inventory. It put the 5 in storage but the 9 disappeared. Wasnt in their inventory or any other chests. Also had a miner take 6 bread I had just crafted from a chest and it vanished without the miner eating any of it.

**Comment by TangoTek** [comment]
Miners frequently 'clean' out their inventory of unwanted blocks.  The criteria for what was removed was very wrong.  Its now been completely changed. Hopefully this shouldn't happen again.
