### ISSUE TITLE
Chef cooks with logs even though minors have already dug up coal

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#34]
i have coal in storage, but there are logs in the furnace

**Comment by gotnate** [comment]
Further, if you pre-stuff the furnace with coal rather than a log, the chef AI eventually shuts down because it wants to put in a log.

**Comment by LiteHorizon** [comment]
Intend. the chef only will cook on a "wood oven"  (this was said in chat by tango)
