### ISSUE TITLE
farmers are neglecting sugarcane

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#35]
i have plenty of other produce, but the sugarcane right around storage remains ignored
![image](https://user-images.githubusercontent.com/69241/55689745-17e0db00-593d-11e9-854d-2f140ce875a4.png)

**Comment by TangoTek** [comment]
Farmer's will stop gathering sugar cane if there is already 128 cane in storage.  In hindsight, this is probably a mistake. I'll remove this limiter.
