### ISSUE TITLE
Immaculate Conception

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/What-If-Villager-Community#36]
Not sure how this one happened, but when I logged back on to the server this morning, I found that my one-villager village had somehow generated two child-hearts despite having only one resident and only one unclaimed bed.

![2019-04-07_14 47 41](https://user-images.githubusercontent.com/49353797/55690327-12878e80-5945-11e9-87f1-25275e653572.png)

**Comment by TangoTek** [comment]
As implemented now, this is possible. It doesn't take two villagers to make a child. It only takes one that is happy when he/she goes to bed and a bit of luck

I fully intend to change this once I get to children, but for now I think this is as intended.
