### ISSUE TITLE
Rancher doesn't go

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#39]
I put animals, and pens out for sheep, chicken, cows and pigs. i put seeds, wheat, sheers and leads in the chest. the rancher picks up some seeds, wheat and sheers, and then does nothing. The leads stay in the chest.

**Comment by TheGreatNaj** [comment]
SAME

**Comment by TangoTek** [comment]
See the chat in discord about Villager Entities.

I made it so that if you go inside an animal pen the "villager animals" will glow
