### ISSUE TITLE
Farmers duplicate hoes

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/What-If-Villager-Community#44]
When a farmer grabs a new, upgraded hoe from storage, they put a copy into their inventory without removing it from storage.

![2019-04-07_17 23 07](https://user-images.githubusercontent.com/49353797/55692162-33a6aa00-595a-11e9-8a60-eca9e6d9388c.png)
![2019-04-07_17 23 12](https://user-images.githubusercontent.com/49353797/55692163-33a6aa00-595a-11e9-8a32-183008e60ced.png)
![2019-04-07_17 24 21](https://user-images.githubusercontent.com/49353797/55692164-33a6aa00-595a-11e9-89c2-a8949e7e7884.png)
![2019-04-07_17 24 24](https://user-images.githubusercontent.com/49353797/55692165-33a6aa00-595a-11e9-8976-c955c3509c57.png)

**Comment by TangoTek** [comment]
Hey Look. I'm an idiot.  Fixed.
