### ISSUE TITLE
Cleric's level up as Guards

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#47]
Rudelle the Cleric has been leveling as a Guard. Intentional, or inherited from guard AI?

![image](https://user-images.githubusercontent.com/69241/55693225-ca776480-5962-11e9-9564-5f41f9687635.png)

**Comment by gotnate** [comment]
she leveled again

![image](https://user-images.githubusercontent.com/69241/55693375-a9634380-5963-11e9-9ac4-2c0143cccf8a.png)

**Comment by TangoTek** [comment]
Great find. Fixed.  Both the Guard and the Cleric share the 'patrol village' AI. When I first wrote it only the guard had it. I removed the skill up chance from patrolling the village.
