### ISSUE TITLE
Guards keep old sword after he upgrads his sword

### ISSUE THREAD

**Issue by LiteHorizon** [TangoTek/What-If-Villager-Community#58]
**Expected behavior**
would think they would put their unused weapon back in storage for someone else to grab.

![image](https://user-images.githubusercontent.com/39017085/55759668-99109e80-5a1f-11e9-818d-535a6a567877.png)

**Comment by TangoTek** [comment]
Fixed. Everyone should trade in their old weapons, tools, armor
