### ISSUE TITLE
Village seems to run while away from the server

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#68]
I came back to the server after being away all day, and found several villagers had gone missing (died), lots of heart tokens, and a well stocked storage chest. Do villages function as chunk loaders?

**Comment by gotnate** [comment]
Command block with a clock and leaving the area confirms that the chunks are unloading.

![image](https://user-images.githubusercontent.com/69241/55771975-22839900-5a3f-11e9-9b8e-9d3d58ba67ee.png)

**Comment by LiteHorizon** [comment]
I was off for 9Hrs all my crops are harvested. so game ticks aren't processing but the villagers are still going

![image](https://user-images.githubusercontent.com/39017085/55821967-463cf280-5ac4-11e9-88b1-63443d3d36be.png)

**Comment by LiteHorizon** [comment]
Fixed
