### ISSUE TITLE
Tavern Bug

### ISSUE THREAD

**Issue by DropDaBassTC** [TangoTek/What-If-Villager-Community#70]
**Describe the bug**
The Tavern has not had any patrons in the last 5 ingame days.  There are chairs and a chef in this building.  No bard, but it sounds like Lite has a bard and is having same issue.

**To Reproduce**
1. Made a Tavern
2. waited and nothing happened

**Expected behavior**
I expect at least a few villagers to go to the tavern, not 0 every night

**Comment by LiteHorizon** [comment]
Villager happiness is almost always too high to go.

**Comment by LiteHorizon** [comment]
Fixed, now a percentage of them will go to the tavern at night even if their happiness is too high to need to go.
