### ISSUE TITLE
Blacksmith crafting limiter

### ISSUE THREAD

**Issue by DropDaBassTC** [TangoTek/What-If-Villager-Community#74]
**Describe the bug**
The blacksmith only makes diamond and iron swords at the moment.

**To Reproduce**
1. input diamonds into storage

**Expected behavior**
Would hope that he would start crafting armor and picks and other tools, but only swords

**Screenshots**

** Logs **
If possible, send your latest.log file in your /logs folder.

**Comment by TangoTek** [comment]
Should be fixed now.
