### ISSUE TITLE
LumberJack AI

### ISSUE THREAD

**Issue by DropDaBassTC** [TangoTek/What-If-Villager-Community#75]
**Describe the bug**
The Lumberjacks will get up in the middle of the night (after going to bed) and go stand out by where the trees are for about 5 minutes and then go back to bed.

**To Reproduce**
Dont know if there are any ways to reproduce it, they just do that at night.

**Expected behavior**
For them to stay in bed

**Screenshots**
I have screenshots upon request, just not sure how to get them to you from here

** Logs **
If possible, send your latest.log file in your /logs folder.

**Comment by TangoTek** [comment]
Looking through things... A villager can wake up in the middle of the night if it senses a thread (zombie). They then get insomnia, which means they can't immediately fall back asleep for a few seconds.

Picking up saplings (a new ai for lumberjacks) wasn't checking for night time. So thats probably what they did.  Fixed that.

Also. Great bug report!
