### ISSUE TITLE
Miners depositing inventory

### ISSUE THREAD

**Issue by DropDaBassTC** [TangoTek/What-If-Villager-Community#77]
**Describe the bug**
I will watch miners with inventories that contain diamonds and ores and the items never ended up in the chests, then just got wiped from the miner's inventory.

**To Reproduce**
1. MIner has 5 diamonds
2. Miner goes into storage
3. Once miner is done eating, will stand there a moment and then leave.

**Expected behavior**
I expect them to place their items in the chests

**Screenshots**
None available at the current momen

** Logs **
TC multiplayer server

**Comment by TangoTek** [comment]
Should be fixed now.  Note miners only deposit things in storage near the end of the day.
