### ISSUE TITLE
Guards and armor

### ISSUE THREAD

**Issue by DropDaBassTC** [TangoTek/What-If-Villager-Community#78]
**Describe the bug**
Placed 2 pieces of armor in the (a diamond helm and a diamond chest piece) and one of the guards came in, grabbed both and only donned the chestpiece, the helm was destroyed. (Not in their inv or in the chest).  There was also a point where I placed 4 helmets in the chest and only 1 got a helm but all 4 were consumed.

**To Reproduce**
1. Place multiple pieces of armor in the chest
2. Let guard come in and pick one
3. watch guard leave with 1 piece of armor equiped bit all pieces consumed.

**Expected behavior**
I expect them to equip what they need and leave the rest in the chest

**Screenshots**

** Logs **
If possible, send your latest.log file in your /logs folder.

**Comment by TangoTek** [comment]
Found the stupidity. Should be fixed
