### ISSUE TITLE
Hitboxes while sleeping

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/What-If-Villager-Community#80]
While sleeping, a villager's hitbox is the same as if they're standing on the foot of their bed. Among other things, this means that to check their stats while sleeping you need to click in empty air above them, and that you can punch a villager out of bed by hitting nothing.

![2019-04-09_11 42 58](https://user-images.githubusercontent.com/49353797/55827045-24407180-5abe-11e9-9165-dfc37a1a795d.png)

**Comment by TangoTek** [comment]
Yep. Known, not really planning on fixing.  Its way too much of a pain to reshape their hitbox without causing more bugs.
