### ISSUE TITLE
Low ceilings block villager sleep

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/What-If-Villager-Community#81]
Because of #80, a two-block ceiling above a villager's bed isn't high enough for them to be able to sleep. If their bed is thus blocked, they can't path to it and can't sleep.

![2019-04-09_11 59 16](https://user-images.githubusercontent.com/49353797/55828006-5521a600-5ac0-11e9-8d09-8ccca66dbe41.png)

**Comment by TangoTek** [comment]
...Yea.  This is an issue, but a minor one in my opinion. I don't think any player would be confused what the problem is. I'm wary of changing the villager hitbox for the new problems that will arise (suffocation, pathing issues, etc)
