### ISSUE TITLE
Blacksmith should prioritize fuel

### ISSUE THREAD

**Issue by Sobertron** [TangoTek/What-If-Villager-Community#83]
**Is your feature request related to a problem? Please describe.**
Blacksmith had coal available as a fuel source but chose to use oak wood logs.

**Describe the solution you'd like**
They should prioritize the fuel available and use the most efficient one. Wood logs should hopefully never be used as a fuel source as they should make charcoal before that happens.

**Comment by OhTheNoises** [comment]
![image](https://user-images.githubusercontent.com/49348348/56406087-b3c3ee00-623d-11e9-99e5-8b93a73e99bb.png)

**Comment by LiteHorizon** [comment]
fixed. 
Chef will still use wood for "cooking on a wood oven"
