### ISSUE TITLE
Chef doesn't recognize coal or charcoal as fuel

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/What-If-Villager-Community#84]
I have coal and charcoal in storage, but the chef refuses to use either of them--after loading the furnace, he stands idle. However, as soon as I added oak logs to the storage, he started using those as fuel.

![2019-04-09_12 29 46](https://user-images.githubusercontent.com/49353797/55830872-c2383a00-5ac6-11e9-867f-4444ddbde131.png)

**Comment by TangoTek** [comment]
Yea, I originally decided to just have the chef only use wood as a fuel. 
1) It seemed way more realistic to cook with a wood fire
2) It puts a drain on the log supply which is desperately needed.

This is open for debate though for sure.
