### ISSUE TITLE
Child Villager pathfinding skips 1-high gaps that would otherwise be valid or required

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#87]
**Describe the bug**
If the path to bed is blocked, except with a 1-high gap at the bottom, child villagers will stop just like adult villagers. The child villager hitbox fits, but I assume that it would require an alternative path-finding world-scan to change the valid blocks the child can navigate to.

![image](https://user-images.githubusercontent.com/69241/55831713-a3d33e00-5ac8-11e9-98c6-b9c14b30fb69.png)

**Comment by TangoTek** [comment]
Yea, you got it. I'd have to generate another full pathing graph. Can't happen.
