### ISSUE TITLE
Villagers read books outside of library

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#88]
This may be related to #6 - Villagers are going to the library (but not in) and reading books.

![image](https://user-images.githubusercontent.com/69241/55831854-fc0a4000-5ac8-11e9-9cd7-255e55d7383a.png)

**Comment by TangoTek** [comment]
Changed them to walk to a random tile within the library rather than just walking near a bookshelf that is in the library
