### ISSUE TITLE
Villagers don't pathfind away from suffocation

### ISSUE THREAD

**Issue by GrifterMage** [TangoTek/What-If-Villager-Community#89]
If you push a block into a villager's head, they won't attempt to pathfind out of being suffocated. If they pathfind for some other reason, so be it, but suffocation damage will not in and of itself cause them to attempt to pathfind.

![2019-04-09_13 03 33](https://user-images.githubusercontent.com/49353797/55831914-29ef8480-5ac9-11e9-90c3-577633cc4ab5.png)

**Comment by TangoTek** [comment]
They no longer take suffocation damage. Getting them to path out of an area that is no longer pathable is pretty hard.
