### ISSUE TITLE
Vanilla Zombie Villagers can be converted to Vanilla Villagers

### ISSUE THREAD

**Issue by gotnate** [TangoTek/What-If-Villager-Community#91]
i saw someone mention this already, but it doesn't look like a bug report was filed. I found a vanilla zombie villager and cured it using vanilla mechanics to get a shepherd

![image](https://user-images.githubusercontent.com/69241/55834327-830de700-5ace-11e9-942f-a13d9ac497ba.png)

**Comment by TangoTek** [comment]
I intentionally didn't do this. If someone wants normal villagers while playing this mod (iron farm, who knows?) then this is the way.
