### ISSUE TITLE
Druid/Miner Range Difference

### ISSUE THREAD

**Issue by TheGreatNaj** [TangoTek/What-If-Villager-Community#93]
Miners will dig out a mineshaft seemingly endlessly while druids only regenerate from such a distance, causing miners to get trapped. 
![2019-04-09_22 54 47](https://user-images.githubusercontent.com/25763105/55849592-33a3d700-5b1f-11e9-9396-72380bf794b3.png)

**Comment by TangoTek** [comment]
Fixed when I redid a lot of miner/druid logic
