### ISSUE TITLE
Vanilla Crops

### ISSUE THREAD

**Issue by TheGreatNaj** [TangoTek/What-If-Villager-Community#96]
Farmers have been harvesting crops and like 1/4 of them are ending up vanilla instead of V-crops
Pic is my chest of vanilla potatoes my farmers have harvested for the few hours Ive been playing today. 
![2019-04-10_02 29 57](https://user-images.githubusercontent.com/25763105/55856575-b38a6b00-5b38-11e9-8649-c61ae273b9dd.png)

**Comment by LiteHorizon** [comment]
Fixed, besides sugar cane but that has its own report on it.
