### ISSUE TITLE
Merchant taking damage before reaching village

### ISSUE THREAD

**Issue by MakaniValur** [TangoTek/What-If-Villager-Community#97]
(I thought I took a screenshot of this, but apparently not, apologies)

The Merchant just got several damage notifications (got damaged by zombie) before he was even close to my village. I couldn't see a glow and I couldn't find him either. And while I didn't get a death notification, the merchant never arrived in town. 

Could it maybe be possible for mobs not to be interested in a merchant? Since the player doesn't know where he'll spawn, it'll be very difficult to light up the area or ensure his safety 100%.

**Comment by TangoTek** [comment]
Yep, it was supposed to be this way all along.  Merchants now have no enemies. Nothing will attack them.
Good find.
